cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views




app_name='cart'
urlpatterns = [
    path('addtocart/<int:i>',views.AddtoCart.as_view(),name='addtocart'),
    path('cartview',views.CartView.as_view(),name='cartview'),
    path('cartdecrement/<int:i>',views.Cartdecrement.as_view(),name='cartdecrement'),
    path('cartremove/<int:i>',views.Cartremove.as_view(),name='cartremove'),
    path('checkout',views.Checkout.as_view(),name='checkout'),
    path('payment/<i>',views.Payment_success.as_view(),name='success'),
    path('orders', views.Orders.as_view(), name='orders'),
]

ecommerce/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart',include('cart.urls')),
    path('search',include('search.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

search/urls.py
from django.contrib import admin
from django.urls import path
from search import views




app_name='search'
urlpatterns = [
    path('',views.SearchView.as_view(),name='search'),

]

shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views

from shop.views import ProductView,DetailView



app_name='shop'
urlpatterns = [
    path('',views.Categoryview.as_view(),name='category'),
    path('product/<int:i>',views.ProductView.as_view(),name='product'),
    path('details/<int:i>',views.DetailView.as_view(),name='details'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('addproducts', views.AddProductView.as_view(), name='addproducts'),
    path('addcategories', views.AddCategoryView.as_view(), name='addcategories'),
    path('addstock/<int:i>', views.AddStockView.as_view(), name='addstock'),

]

cart/models.py
from django.db import models

from shop.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)
# Create your models here.
    def __str__(self):
        return self.user.username
    def subtotal(self):
        return self.product.price*self.quantity

from django.utils import timezone
class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    amount=models.IntegerField()
    order_id=models.CharField(max_length=20)
    phone=models.IntegerField(null=True)
    address=models.TextField()
    payment_method=models.CharField(max_length=20)
    order_date=models.DateTimeField(auto_now=True)
    is_ordered = models.BooleanField(default=False)
    delivery_status=models.BooleanField(default=False)
    def __str__(self):
        return self.user.username

class Order_items(models.Model):
    order=models.ForeignKey(Order,on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity=models.IntegerField()
    def __str__(self):
        return self.product.name

search/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from cart.models import Order
class OrderForm(forms.ModelForm):
    payment_choices=[('cod','COD'),('online','ONLINE')]
    payment_method=forms.ChoiceField(choices=payment_choices)
    class Meta:
        model=Order
        fields=['address','phone','payment_method']

cart/views.py
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from shop.models import Product
from cart.models import Cart
from django.contrib import messages
import razorpay

from cart.models import Order,Order_items


class AddtoCart(View):
    def get(self,request,i):
        p=Product.objects.get(id=i)
        u=request.user
        try:
            c=Cart.objects.get(user=u,product=p)
            c.quantity+=1
            c.save()
        except:
            c=Cart.objects.create(user=u,product=p,quantity=1)
            c.save()
        return redirect('cart:cartview')
class CartView(View):
    def get(self,request):
        u=request.user
        c=Cart.objects.filter(user=u)
        total = 0
        for i in c:
            total += i.product.price * i.quantity
        context = {'cart': c, 'total': total}
        return render(request,'cart.html',context)
class Cartdecrement(View):
    def get(self,request,i):
        p=Product.objects.get(id=i)
        u=request.user
        try:
            c=Cart.objects.get(product=p,user=u)
            if(c.quantity>1):
                c.quantity-=1
                c.save()
            else:
                c.delete()
        except:
            pass
        return redirect('cart:cartview')
class Cartremove(View):
    def get(self,request,i):
        p=Product.objects.get(id=i)
        u=request.user
        try:
            c=Cart.objects.get(product=p,user=u)
            c.delete()
        except:
            pass
        return redirect('cart:cartview')
from cart.forms import OrderForm
def checkstock(c):
    stock=True
    for i in c:
        if i.product.stock<i.quantity:
            stock=False
            break
    else:
        stock=True
    return stock
import uuid
class Checkout(View):
    def post(self,request):
        print(request.POST)
        form_instance=OrderForm(request.POST)
        if form_instance.is_valid():
            o=form_instance.save(commit=False)
            u=request.user
            o.user=u
            c = Cart.objects.filter(user=u)

            total = 0
            for i in c:
                total += i.product.price * i.quantity
            o.amount = total
            o.save()
            if(o.payment_method=='online'):
                client=razorpay.Client(auth=('rzp_test_ReWDUyUM9SBdUY','t6uSZ6L3a3JnA2Cj2UZpZn2e'))
                print(client)
                response_payment=client.order.create(dict(amount=total*100,currency='INR'))
                print(response_payment)
                id=response_payment['id']
                o.order_id=id
                o.save()
                context={'payment':response_payment}
            else:
                o.is_ordered=True
                uid=uuid.uuid4().hex[::14]
                c = Cart.objects.filter(user=u)
                id='order_COD'+uid
                o.order_id=id
                o.save()
                for i in c:
                    items = Order_items.objects.create(order=o, product=i.product, quantity=i.quantity)
                    items.save()
                    items.product.stock -= items.quantity
                    items.product.save()

        return render(request,'payment.html',context)
    def get(self,request):
        u=request.user
        c=Cart.objects.filter(user=u)
        stock=checkstock(c)
        if stock:
            form_instance=OrderForm()
            context={'forms':form_instance}
            return render(request,'checkout.html',context)
        else:
            messages.error(request,'cant place order')
            return render(request, 'checkout.html')
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.contrib.auth import login
@method_decorator(csrf_exempt,name="dispatch")
class Payment_success(View):
    def post(self,request,i):
        u = User.objects.get(username=i)
        login(request, u)
        response=request.POST
        print(response)
        id=response['razorpay_order_id']
        print(id)

        order = Order.objects.get(order_id=id)
        order.is_ordered = True  # after successful completion of order
        order.save()

        # order_items
        c = Cart.objects.filter(user=u)
        for i in c:
            o = Order_items.objects.create(order=order, product=i.product, quantity=i.quantity)
            o.save()
            o.product.stock-=o.quantity
            o.product.save()

            c.delete()
        return render(request,'payment_success.html')
class Orders(View):
    def get(self,request):
        u=request.user
        o=Order.objects.filter(user=u,is_ordered=True)
        context={'orders':o}
        return render(request,'orders.html',context)
# Create your views here.

search/views.py
from itertools import product

from django.shortcuts import render
from django.views import View
from django.db.models import Q
from shop.models import Product
# Create your views here.
class SearchView(View):
    def get(self,request):
        query=request.GET['q']
        print(query)
        if query:
            p=Product.objects.filter(Q(name__icontains=query)|Q(description__icontains=query)|Q(price__icontains=query))
            context={'products':p}
        return render(request,'search.html',context)

templates/addcategories.html
{% extends 'base.html' %}
{% block content %}
<div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Add categories</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">ABOUT US</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<div class="container mb-3 mt-2">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>
    </div>
{% endblock %}

templates/addproducts.html
<!DOCT{% extends 'base.html' %}
{% block content %}
<div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Add products</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">ABOUT US</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<div class="container mb-3 mt-2">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>
    </div>
{% endblock %}

templates/addstock.html
<!DOCT{% extends 'base.html' %}
{% block content %}
<div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>product stock</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">ABOUT US</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<div class="container mb-3 mt-2">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>
    </div>
{% endblock %}

templates/cart.html
{% extends 'base.html' %}
{% block content %}

 <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Cart</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Cart</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Title Box -->
    <!-- Start Cart  -->
    <div class="cart-box-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-main table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Images</th>
                                    <th>Product Name</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>SubTotal</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for i in cart %}
                                <tr>
                                    <td class="thumbnail-img">
                                        <a href="#">
									<img class="img-fluid" src="{{i.product.image.url}}" alt="" />
								</a>
                                    </td>
                                    <td class="name-pr">
                                        <a href="#">
                                            {{i.product.name}}
								</a>
                                    </td>
                                    <td class="price-pr">
                                        <p>{{i.product.price}}</p>
                                    </td>
                                    <td class="quantity-box"><p>{{i.quantity}}</p></td>
                                    <td class="total-pr">
                                        <p>{{i.subtotal}}</p>
                                    </td>
                                    <td class="remove-pr">
                                        {% if i.product.stock > 0 %}
                                           <a href="{% url 'cart:cartdecrement' i.product.id %}">
									<i class="fas fa-minus"></i>
								</a>
                                           <a href="{% url 'cart:addtocart' i.product.id %}">
									<i class="fas fa-plus"></i>
								</a>
                                        <a href="{% url 'cart:cartremove' i.product.id %}">
									<i class="fas fa-times"></i>
								</a>
                                        {% else %}
                                         <a href="{% url 'cart:cartdecrement' i.product.id %}">
									<i class="fas fa-minus"></i>
								</a>

                                        <a href="{% url 'cart:cartremove' i.product.id %}">
									<i class="fas fa-times"></i>
								</a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="row my-5">
                <div class="col-lg-8 col-sm-12"></div>
                <div class="col-lg-4 col-sm-12">
                    <div class="order-box">
                        <h3>Order summary</h3>
                        <div class="d-flex">
                            <h4>Total</h4>
                            <div class="ml-auto font-weight-bold"> {{total}}</div>
                        </div>
                        <div class="d-flex">
                            <h4>shipping cost</h4>
                            <div class="ml-auto font-weight-bold"> $ 40 </div>
                        </div>

                        <hr>
                        <div class="d-flex gr-total">
                            <h5>grand Total</h5>
                            <div class="ml-auto h5"> {{total}}</div>
                        </div>
                        <hr> </div>
                </div>
                <div class="col-12 d-flex shopping-box"><a href="{% url 'cart:checkout' %}" class="ml-auto btn hvr-hover">Checkout</a> </div>
            </div>

        </div>
    </div>
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% block content %}
<!--slider-->
<div id="slides-shop" class="cover-slides">
        <ul class="slides-container">
            <li class="text-center">
                <img src="images/banner-01.jpg" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> Freshshop</strong></h1>
                            <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                            <p><a class="btn hvr-hover" href="#">Shop New</a></p>
                        </div>
                    </div>
                </div>
            </li>
            <li class="text-center">
                <img src="images/banner-02.jpg" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> Freshshop</strong></h1>
                            <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                            <p><a class="btn hvr-hover" href="#">Shop New</a></p>
                        </div>
                    </div>
                </div>
            </li>
            <li class="text-center">
                <img src="images/banner-03.jpg" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> Freshshop</strong></h1>
                            <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                            <p><a class="btn hvr-hover" href="#">Shop New</a></p>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
        <div class="slides-navigation">
            <a href="#" class="next"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
            <a href="#" class="prev"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
        </div>
    </div>

<div class="products-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="title-all text-center">
                        <h1>our collection</h1>
                        <p style="text-align:justify;line-height:2">Lorem ipsum dolor sit amet,Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.  consectetur adipiscing elit. Sed sit amet lacus enim.</p>
                    </div>
                </div>
            </div>
</div>
</div>

 <div class="categories-shop">
        <div class="container">
            <div class="row">
                {% for i in categories %}
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="shop-cat-box">
                        <img class="" src="{{i.image.url}}" alt="" height="300px" width="100%"/>
                        <a class="btn hvr-hover" href="{% url 'shop:product' i.id %}">{{i.name}}</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block content %}
<h1>login</h1>
<form method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>
{% endblock %}

templates/orders.html
{% extends 'base.html' %}
{% block content %}
<!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Orders</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Checkout</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/payment.html
{% extends 'base.html' %}
{% block content %}
<!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Payment</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Checkout</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

<div class="container mt-5 p-5">
    {% if payment %}
<form action="{% url 'cart:success' user.username%}" method="POST">
<script
   src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_ReWDUyUM9SBdUY"
    data-amount={{payment.amount}}
    data-currency="INR"
    data-order_id={{payment.id}}
    data-buttontext="Pay with Razorpay"
    data-name="Acme Corp"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="Gaurav Kumar"
    data-prefill.email="gaurav.kumar@example.com"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
    {% else %}
    <h4>your order placed succesfully</h4>
{% endif %}
</div>
{% endblock %}

templates/payment_success.html
{% extends 'base.html' %}
{% block content %}
<!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Payment</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Checkout</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<div class="container mt-5 p-5">
    <h2>your order is placed successfully</h2>
</div>
{% endblock %}

templates/product.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <img src="{{category.image.url}}" height="400px" width="100%">
</div>
<div class="products-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="title-all text-center">
                        <h1>{{category.name}}</h1>
                        <p>{{category.description}}</p>
                    </div>
                </div>
            </div>


        <div class="row special-list">
            {% for j in category.products.all %}
    <div class="col-lg-3 col-md-6 special-grid best-seller">

        <div class="products-single fix">
            <div class="box-img-hover">
                <img src="{{j.image.url}}" class="img-fluid" alt="Image">
                <div class="mask-icon">
                    <ul>
                        <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>
                        <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                        <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                    </ul>
                    <a class="cart" href="#">Add to Cart</a>
                </div>
            </div>
            <div class="why-text">
                <h4>{{j.name}}</h4>
                <h5>{{j.price}}</h5>
            </div>
        </div>

    </div>
            {% endfor %}
    </div>

        </div>

{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block content %}
<div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>ABOUT US</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">ABOUT US</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<div class="container mb-3 mt-2">
<form method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>
    </div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% block content %}
<div class="products-box">
        <div class="container">
            {% if products %}
            <div class="row">
                <div class="col-lg-12">
                    <div class="title-all text-center">
                        <h1>{{category.name}}</h1>
                        <p>{{category.description}}</p>
                    </div>
                </div>
            </div>


        <div class="row special-list">
            {% for j in products %}
    <div class="col-lg-3 col-md-6 special-grid best-seller">

        <div class="products-single fix">
            <div class="box-img-hover">
                <img src="{{j.image.url}}" class="img-fluid" alt="Image">
                <div class="mask-icon">
                    <ul>
                        <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>
                        <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                        <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                    </ul>
                    <a class="cart" href="{% url 'shop:details' j.id %}">details</a>
                </div>
            </div>
            <div class="why-text">
                <h4>{{j.name}}</h4>
                <h5>{{j.price}}</h5>
            </div>
        </div>

    </div>
            {% endfor %}
            {% else %}
            <h2>no results</h2>
            {% endif %}
    </div>

        </div>
{% endblock %}